var DB2 = {
    "beverages" :
        [{
            "nr": "10001",
            "artikelid": "25053",
            "varnummer": "100",
            "namn": "Braastad XO",
            "namn2": "",
            "prisinklmoms": "442.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2000-08-07",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Cognac, Fine Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Tiffon",
            "leverantor": "Arcus Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"4",
            "available": true,
            "category":"Spirit"
            
        }, {
            "nr": "1001",
            "artikelid": "190719",
            "varnummer": "10",
            "namn": "Vanlig Vodka",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Svensk Export Vodka AB",
            "leverantor": "Fondberg",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1001201",
            "artikelid": "51029",
            "varnummer": "10012",
            "namn": "Dworek Vodka",
            "namn2": "",
            "prisinklmoms": "190.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2004-12-06",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Polen",
            "producent": "Tarpan Fabryka Likierow",
            "leverantor": "TIWA Trading AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": false,
            "category":"Spirit"
        }, {
            "nr": "1001202",
            "artikelid": "407506",
            "varnummer": "10012",
            "namn": "Dworek Vodka",
            "namn2": "",
            "prisinklmoms": "100.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Polen",
            "producent": "Tarpan Fabryka Likierow",
            "leverantor": "TIWA Trading AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"3",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1003802",
            "artikelid": "513291",
            "varnummer": "10038",
            "namn": "Esping Jul B\u00c3\u00a4sk",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-11-15",
            "slutlev": " ",
            "varugrupp": "Kryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Symposion International",
            "leverantor": "Symposion International AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "32%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1004703",
            "artikelid": "723841",
            "varnummer": "10047",
            "namn": "Nils Oscar",
            "namn2": "Celebration Ale",
            "prisinklmoms": "43.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-02-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Nils Oscar Company",
            "leverantor": "The Nils Oscar Company AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "9.4%",
            "modul": "T5",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1004801",
            "artikelid": "733051",
            "varnummer": "10048",
            "namn": "Rhum J. M",
            "namn2": "",
            "prisinklmoms": "729.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Rom, M\u00c3\u00b6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Martinique",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Heritiers Crassous de Mede",
            "leverantor": "Cask Sweden AB",
            "argang": "2001",
            "provadargang": "",
            "alkoholhalt": "46.6%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": false,
            "category":"Spirit"
        }, {
            "nr": "1004901",
            "artikelid": "733068",
            "varnummer": "10049",
            "namn": "Rhum J.M",
            "namn2": "",
            "prisinklmoms": "1399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Rom, M\u00c3\u00b6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Martinique",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Heritiers Crassous de Mede",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "44.8%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1005001",
            "artikelid": "733084",
            "varnummer": "10050",
            "namn": "Balcones Texas",
            "namn2": "",
            "prisinklmoms": "899.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Whisky, Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Balcones Distilling",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "52.2%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1005101",
            "artikelid": "733200",
            "varnummer": "10051",
            "namn": "Balcones Brimstone",
            "namn2": "",
            "prisinklmoms": "899.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Whisky, \u00c3\u2013vrig",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Balcones Distilling",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "53.2%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1005201",
            "artikelid": "733236",
            "varnummer": "10052",
            "namn": "Balcones True Blue",
            "namn2": "",
            "prisinklmoms": "899.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Whisky, \u00c3\u2013vrig",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Balcones Distilling",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "50.2%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"3",
            "available": false,
            "category":"Spirit"
        }, {
            "nr": "1005401",
            "artikelid": "733429",
            "varnummer": "10054",
            "namn": "Linkwood",
            "namn2": "the Octave",
            "prisinklmoms": "1159.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Whisky, Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland, Highlands, Speyside",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Duncan Taylor Scotch Whisky",
            "leverantor": "Clydesdale AB",
            "argang": "1989",
            "provadargang": "",
            "alkoholhalt": "51.7%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1005502",
            "artikelid": "733446",
            "varnummer": "10055",
            "namn": "Marolo",
            "namn2": "Grappa di Arneis Vigneto Renesio",
            "prisinklmoms": "481.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Grappa och Marc, Grappa",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "",
            "ursprunglandnamn": "Italien",
            "producent": "Distilleria St Teresa dei Frat",
            "leverantor": "Haugen-Gruppen AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "50%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1005602",
            "artikelid": "733468",
            "varnummer": "10056",
            "namn": "Cl\u00c3\u00a9ment",
            "namn2": "Single Cask",
            "prisinklmoms": "529.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Rom, M\u00c3\u00b6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Martinique",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Heritiers Crassous de Mede",
            "leverantor": "Cask Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "47.6%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "101",
            "artikelid": "1",
            "varnummer": "1",
            "namn": "Renat",
            "namn2": "",
            "prisinklmoms": "203.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1993-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt m\u00c3\u00a4rke",
            "producent": "Pernod Ricard",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1010001",
            "artikelid": "817007",
            "varnummer": "10100",
            "namn": "Romano Levi",
            "namn2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
            "prisinklmoms": "790.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-04-01",
            "slutlev": " ",
            "varugrupp": "Grappa och Marc, Grappa",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Italien",
            "producent": "Distilleria Levi Serafino ( di",
            "leverantor": "Haugen-Gruppen AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1010404",
            "artikelid": "611864",
            "varnummer": "10104",
            "namn": "Giare 5 Grappe",
            "namn2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
            "prisinklmoms": "399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-03-01",
            "slutlev": " ",
            "varugrupp": "Grappa och Marc, Grappa",
            "forpackning": "5 flaskor \u00c3\u00a0 100 ml",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Italien",
            "producent": "Marzadro",
            "leverantor": "Stragas-Gruppen AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "TST",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        }, {
            "nr": "1010501",
            "artikelid": "659534",
            "varnummer": "10105",
            "namn": "Genuin 25",
            "namn2": "",
            "prisinklmoms": "149.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-09-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Svensk Vodka i Motala AB",
            "leverantor": "Svensk Vodka i Motala AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "25%",
            "modul": "",
            "sortiment": "TST",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Spirit"
        },  {
            "nr": "1159803",
            "artikelid": "506905",
            "varnummer": "11598",
            "namn": "Innis & Gunn",
            "namn2": "Rum Finish Oak Aged Beer",
            "prisinklmoms": "19.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Innis & Gunn",
            "leverantor": "TOMP Beer Wine & Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.8%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Beer"
        },  {
            "nr": "1162001",
            "artikelid": "861392",
            "varnummer": "11620",
            "namn": "MAD",
            "namn2": "Salt",
            "prisinklmoms": "84.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-05",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt m\u00c3\u00a4rke",
            "producent": "MAD Beer",
            "leverantor": "Brill & Co AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Beer"
        },  {
            "nr": "1167601",
            "artikelid": "671499",
            "varnummer": "11676",
            "namn": "Vieille Brune",
            "namn2": "",
            "prisinklmoms": "149.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-08-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "Brasserie Thiriez",
            "leverantor": "Brekeriet Beer AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.5%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Beer"
        },   {
            "nr": "1167801",
            "artikelid": "670730",
            "varnummer": "11678",
            "namn": "Double Old Thumper",
            "namn2": "Ale",
            "prisinklmoms": "71.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-08-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Shipyard Brewing",
            "leverantor": "World Beer Trading KB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "11.2%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Beer"
        }, {
            "nr": "1200201",
            "artikelid": "33861",
            "varnummer": "12002",
            "namn": "Allesverloren",
            "namn2": "Tinta Barocca",
            "prisinklmoms": "125.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-04-02",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Western Cape, Coastal Region, Swartland",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Allesverloren Wine Estate",
            "leverantor": "janake wine group AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        },  {
            "nr": "1209408",
            "artikelid": "36202",
            "varnummer": "12094",
            "namn": "Robertson",
            "namn2": "Chardonnay",
            "prisinklmoms": "189.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-10-07",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Fylligt & Smakrikt",
            "forpackning": "Box",
            "forslutning": "Vridtapp",
            "ursprung": "Western Cape",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Robertson Winery",
            "leverantor": "Prime Wine Sweden AB",
            "argang": "2014",
            "provadargang": "2014",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        },  {
            "nr": "1209502",
            "artikelid": "732557",
            "varnummer": "12095",
            "namn": "Grythyttan Hjortron",
            "namn2": "",
            "prisinklmoms": "166.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Fruktvin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "\u00c3\u2013rebro l\u00c3\u00a4n, \u00c3\u2013rebro kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Grythyttan Vin AB",
            "leverantor": "Grythyttan Vin",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        },  {
            "nr": "1210304",
            "artikelid": "38507",
            "varnummer": "12103",
            "namn": "JP Chenet",
            "namn2": "Colombard Sauvignon blanc",
            "prisinklmoms": "26.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2003-02-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "JP Chenet",
            "leverantor": "Stellan Kramer AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "11.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        },   {
            "nr": "1210502",
            "artikelid": "643373",
            "varnummer": "12105",
            "namn": "Hubert Beck",
            "namn2": "R\u00c3\u00a9serve du Chevalier Pinot Gris",
            "prisinklmoms": "49.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-04-02",
            "slutlev": " ",
            "varugrupp": "Vitt vin, Torrt, Druvigt & Blo",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Hubert Beck",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        }, {
            "nr": "1210901",
            "artikelid": "190603",
            "varnummer": "12109",
            "namn": "Allesverloren",
            "namn2": "Fine Old Vintage",
            "prisinklmoms": "145.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013vrigt starkvin",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Western Cape, Coastal Region, Swartland",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Allesverloren Wine Estate",
            "leverantor": "janake wine group AB",
            "argang": "2009",
            "provadargang": "2009",
            "alkoholhalt": "20.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        }, {
            "nr": "1211908",
            "artikelid": "190625",
            "varnummer": "12119",
            "namn": "Rijk's",
            "namn2": "Shiraz Cinsault Mourv\u00c3\u00a8dre Viognier",
            "prisinklmoms": "179.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "R\u00c3\u00b6tt vin",
            "forpackning": "Box",
            "forslutning": "Tryckknapp topp",
            "ursprung": "Western Cape",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Rijks Private Cellar",
            "leverantor": "Prime Wine Sweden AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "14%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "stock":"50",
            "available": true,
            "category":"Wine"
        },
    ]}
module.exports = DB2;